### PR TITLE
composer update failed

### PR DESCRIPTION
**Pull request by demsey2**
Changed BigElephant\Presenter\View\Environment::make() to be compatible with the latest version of L4

ErrorException: Runtime Notice: Declaration of BigElephant\Presenter\View\Environment::make() should be compatible with Illuminate\View\Environment::make($view, $data = Array) in /Users/dawid/server/o2c/vendor/bigelephant/presenter/src/BigElephant/Presenter/View/Environment.php line 9

### CODE REVIEW

**Comment by mario** [comment]
Hi,

is this going to get merged in soon? Its breaking everything :)

**Comment by richlove1** [comment]
Yeah just come to post the same issue, have fixed locally be handy to have this on master

**Comment by andrew13** [comment]
Yes please update this

**Comment by robclancy** [comment]
Sorry about the delay guys, been offline since 2 days ago. Didn't actually know anyone used this. I will be making an update to it today or at least this week. It will probably be moved to robclancy/presenter as well however I'll make a script to keep this repo updated as read only so things don't need to be changed.

**Pull request merged**
